global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'airflow'
    static_configs:
      - targets: ['webserver:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
